[package]
name = "hello-triangle-rust"
description = "A collection of OpenGL programs written in the Rust programming language"
repository = "https://github.com/platc2/opengl-rust"
keywords = ["OpenGL", "Rust"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.2", features = ['bundled', 'static-link'] }
imgui = "0.10.0"
gl = { path = "./lib/gl"}
nalgebra-glm = "0.18.0"
stb_image = "0.2.4"
thiserror = "1.0.37"
noise = "0.8.1"
anyhow = "1.0.65"

[build-dependencies]
walkdir = "2.3.2"

[[bin]]
name = "hello_triangle"

[[bin]]
name = "sobel_cube"

[[bin]]
name = "terrain"
