[package]
name = "hello-triangle-rust"
description = "A collection of OpenGL programs written in the Rust programming language"
repository = "https://github.com/platc2/opengl-rust"
keywords = ["OpenGL", "Rust"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.htmls

[dependencies]
sdl2 = { version = "0.35.2", features = ['bundled', 'static-link']}
imgui = "0.11.0"
gl = { path = "./lib/gl"}
nalgebra-glm = "0.18.0"
stb_image = "0.2.5"
thiserror = "1.0.40"
noise = "0.8.2"
anyhow = "1.0.70"
once_cell = "1.18.0"

[build-dependencies]
walkdir = "2.3.2"

[[bin]]
name = "hello_triangle"

[[bin]]
name = "sobel_cube"

[[bin]]
name = "terrain"

[[bin]]
name = "bruteforce_terrain"

[[bin]]
name = "atmospheric_scattering"

[[bin]]
name = "tessellation"

[[bin]]
name = "planet_renderer"
