[package]
name = "hello-triangle-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35.2", features = ['bundled', 'static-link'] }
imgui-rs = "1.47.0"
gl = "0.14.0"
